# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dieter De Paepe
email: dieter.depaepe[at]gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dieter De Paepe is a computer scientist working as researcher at iMinds.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dieterdepaepe.github.io" # the base hostname & protocol for your site
collections: 
#- publications
  publications:
    output: true
    permalink: /publications/:title/
defaults:
  -
    scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
twitter_username: DieterDePaepe
github_username:  dieterdepaepe
linkedin_username: dieterdepaepe

# Build settings
markdown: kramdown
